name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  # OPPO
  ## Vsmart
  build-vsmart-joy-3-based-aosp-a15:
    name: "Vsmart Joy 3 (Based AOSP - A15)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-joy3.yml
    secrets: inherit

  # Xiaomi

  ## Redmi
